Submission of first weekly assignment.
Teaching-projects/SZE-MOSZE-2020-Random pull request #1
Opened 2020-09-11 14:23 UTC by LengyHELL

2020-09-16 14:28 UTC, wajzy requested changes
Sziasztok!
2 fő gond van:
1) Nem azt csinálja a program, amit kellene. Parancssorból kellene kiolvasnia az adatokat, nem pedig véletlenszerűen generálni.
2) Az OO alapelveket nem tartjátok tiszteletben, nem OO a kód.
Kérem javítani ezeket.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  Mob m2("Goliath", random(300, 750), random(5, 10));
Parancssori argumentumokból kell kiolvasni az átadott értékeket!

2020-09-16 14:28 UTC, wajzy commented on README.md
> +* **random** - this function uses rand() to create a random number for a given interval
Most úgy néz ki, ez nem fog kelleni.

2020-09-16 14:28 UTC, wajzy commented on README.md
> +The main program generates two monsters with slightly randomized health and attack points, and plays the battle between them until one of them loses its health points.
Nem erről szólt a feladat:

$ ./a.out Maple 150 10 Sally 45 30
Maple: HP: 150, DMG: 10
Sally: HP: 45, DMG: 30
Maple -> Sally
Maple: HP: 150, DMG: 10
Sally: HP: 35, DMG: 30
Sally -> Maple
Maple: HP: 120, DMG: 10
Sally: HP: 35, DMG: 30
Maple -> Sally
Maple: HP: 120, DMG: 10
Sally: HP: 25, DMG: 30
Sally -> Maple
Maple: HP: 90, DMG: 10
Sally: HP: 25, DMG: 30
Maple -. Sally
Maple: HP: 90, DMG: 10
Sally: HP: 15, DMG: 30
Sally -> Maple
Maple: HP: 60, DMG: 10
Sally: HP: 15, DMG: 30
Maple -> Sally
Maple: HP: 60, DMG: 10
Sally: HP: 5, DMG: 30
Sally -> Maple
Maple: HP: 30, DMG: 10
Sally: HP: 5, DMG: 30
Maple -> Sally
Maple: HP: 30, DMG: 10
Sally: HP: 0, DMG: 30
Sally died. Maple wins.
$

Azaz hp és dmg értéke nem véletlenszerű, hanem parancssorban adott, és a karakterek megadásának sorrendje dönti el, ki sebez először.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +#include <time.h>
Ha ez csak a random miatt kellett, akkor nem kell.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +struct Mob {
Miért nem class?

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  ~Mob() {}
Ez minek kell, ha nem csinál semmit?

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  float damage = 0;
Itt nem valósul meg az adatrejtés elve.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  os << mob.name << "(HP:" << mob.health << ", DMG:" << mob.damage << ")";
Itt látszik, mennyire nem.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +}
A feladatkiírás miatt erre (egyelőre legalábbis) nincs szükség.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +}
Itt meg az egységbezárás elve nem érvényesül. Ez most egy függvény, aminek semmi köze a karakterekhez. A logikai kapcsolatnak valahogy meg kellene jelennie a kódban.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  srand(time(NULL));
Megint csak nem fog kelleni.

2020-09-16 14:28 UTC, wajzy commented on main.cpp
> +  }
Hm. Ha m1 első támadása során m2 egyből meghal, akkor azért még visszaüt?

2020-09-16 15:56 UTC, LengyHELL commented
@wajzy , köszönöm a visszajelzést, elméletileg javítottam a hibákat

2020-09-17 18:50 UTC, wajzy approved these changes
OK, én ezt elfogadom.

2020-09-17 18:50 UTC, wajzy commented on main.cpp
> +  std::cout << dmg2 << std::endl;
Hm?

2020-09-17 19:05 UTC, LengyHELL commented on main.cpp
> +  std::cout << dmg2 << std::endl;
A kiírás csak teszteléshez kellett, de véletlenül benn maradt

2020-09-18 09:10 UTC, merged