Second weekly submission
Teaching-projects/SZE-MOSZE-2020-Random pull request #2
Opened 2020-09-23 20:51 UTC by LengyHELL

2020-09-27 13:30 UTC, LengyHELL commented
@wajzy , legyen szíves reviewelje a kódot. Előre is köszönöm.

2020-09-29 06:55 UTC, wajzy requested changes
A feladat nem specifikálta pontosan, hogy milyen szabályok vonatkoznak a karakterek névadására, azaz megengedett-e bennük pl. a szóköz használata, vagy sem. Ebből kifolyólag a parzolás lehetséges hibáját a szóközt tartalmazó neveknél semmiképpen nem tartom súlyos gondnak, főleg, hogy a mi kiadott mintáinkban sem szerepeltek ilyen nevek.
Viszont a feladatkiírás statikus parseUnit függvényt kért, és a tiétek nem olyan. Ezzel mindenképpen foglalkozzatok!

2020-09-29 06:55 UTC, wajzy commented on unit.cpp
> +    }
Ez elég veszélyes. Nekem úgy tűnik, hogy ha pl. a unit neve szóközt tartalmaz, azokat kitörlöd a nevéből. Ez megérne egy tesztet. Szóval, ha egy idézőjeles rész belsejében jársz, szerintem ne töröld a szóközöket.

2020-09-29 06:55 UTC, wajzy commented on unit.hpp
> +  void parse_unit(const std::string& filename);
Ez nem statikus függvény.

2020-09-29 08:02 UTC, LengyHELL commented
@wajzy javítottam a hibákat.

2020-09-29 09:00 UTC, wajzy approved these changes
@hegyhati Elegánsabb lett volna, ha nem a privát adattagokat írjátok át (amit nem tilt a fordító, mert ugyanolyan osztályból történik a módosítás), hanem segédváltozóba gyűjtitek az adatokat, és ezeket adjátok át a konstruktornak, ami majd beírja őket a helyükre. De legyen, azért így is elfogadom.

2020-09-29 12:07 UTC, merged