Levelup
Teaching-projects/SZE-MOSZE-2020-Random pull request #4
Opened 2020-10-15 17:30 UTC by LengyHELL

2020-10-17 14:31 UTC, oliverosz requested changes

2020-10-17 14:31 UTC, oliverosz commented on player.cpp
> +    xp += damage;
Csak annyi xp-t kapjon, amennyi sérülést az ellenfél ténylegesen elszenvedett. Ha kevesebb élete volt, akkor kevesebbet.

2020-10-17 14:31 UTC, oliverosz commented on player.cpp
> +#include "math.h"
`<cmath>`

2020-10-17 14:31 UTC, oliverosz commented on player.hpp
> +  Player() : Unit("", 0, 0), max_hp(0), max_xp(100), xp(0), level(0) {}
Itt nem kell még egyszer megadni a kezdőértéket, ha van nekik default érték adva deklarációnál.

2020-10-17 14:31 UTC, oliverosz commented on player.cpp
> +      damage = floor(damage * 1.1);
A floor nem kerekítés.

2020-10-17 14:31 UTC, oliverosz commented on unit.hpp
> +  void attack(Unit& other);
Legyen virtuális ez a metódus.

2020-10-17 15:22 UTC, LengyHELL commented
@oliverosz javítottam a hibákat.

2020-10-19 16:17 UTC, oliverosz commented
OK, így már jó a levelup feature implementációja. Viszont a branch le van maradva a mastertől. Frissíteni kell a branchet, és feloldani a konfliktusokat.

2020-10-19 18:42 UTC, LengyHELL commented
@oliverosz feloldottam a conflictokat.

2020-10-20 15:32 UTC, oliverosz approved these changes

2020-10-20 15:32 UTC, merged