Jsonparser
Teaching-projects/SZE-MOSZE-2020-Random pull request #6
Opened 2020-10-16 03:22 UTC by LengyHELL

2020-10-20 20:09 UTC, LengyHELL commented
@wajzy feloldottam a conflictokat.

2020-10-22 13:07 UTC, wajzy requested changes
Nincs semmi komoly gond, de azt szeretném még kérni, hogy legyen tesztelve a kivétel dobása is 1-2 esetben.

2020-10-22 13:07 UTC, wajzy commented on json.cpp
> +    parse_raw(data);
Ennek a résznek az ismétlődését jó lett volna elkerülni.

2020-10-22 20:01 UTC, LengyHELL commented
@wajzy javítottam a redundanciát és megírtam az exception teszteket.

2020-10-24 14:07 UTC, wajzy approved these changes
OK

2020-10-24 14:07 UTC, merged